### ISSUE TITLE
auth token technical discussion / question

### ISSUE THREAD

**Issue by seanmakesgames** [DrizzlyBear/hackmud_chat_web#92]
I'd like to have an attach point for just providing an auth token for the chat api, bypassing the chat_pass auth flow, so I can easily set up oauth integration with the webchat deployment on the hackmud web servers.

Is there a way to do this already? If so, give me some details about that.

If not, this is a request for that work. :D

**Comment by hackmud-dtr** [comment]
Ultimately you'll need some way to say "this is my account". That's either from the client ("this is my account because look the client agrees") or a steam login ("this is my account because look, steam agrees"). Client is much less painful than steam login, but of course client requires more than just a website...

Worth noting: if you save your chat_token, the web chat website will accept that in the chat_pass box. It's not advertised but it handles it. So you can just save your chat token and use that.

**Comment by seanmakesgames** [comment]
yes.
